import { ThemeProvider } from "next-themes";
import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/footer/Footer";
import { Montserrat } from "next/font/google";
import Navbar from "./components/navbar/Navbar";

export const metadata: Metadata = {
  title: "Shreyash Balapure - Portfolio",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-montserrat",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.ico" type="image/x-icon" />
      <body className={montserrat.className}>
        {" "}
        <ThemeProvider attribute="class">
          <Navbar/>
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
